### ISSUE TITLE
Openhivenpy on Visual Studio

### ISSUE THREAD

**Issue by CaptainKnuddel** [Nicolas-Klatzer/openhiven.py#67]
**Describe the bug**
C:\Users\Lorenz\AppData\Roaming\Python\Python37\site-packages\openhivenpy\gateway\ws.py:235: RuntimeWarning: coroutine 'Websocket.ws_connect.<locals>.ws_connection' was never awaited
  self._connection_task = asyncio.create_task(ws_connection(), name="openhivenpy-ws-connection")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Lorenz\AppData\Roaming\Python\Python37\site-packages\openhivenpy\gateway\connection.py:128: RuntimeWarning: coroutine 'Client.__check_if_data_is_complete' was never awaited
  _tasks.append(asyncio.create_task(async_task(), name=task_name))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Idk whats wrong it just doesnt work (Python3.7)

**Comment by Nicolas-Klatzer** [comment]
Can you try to explain the issue a bit better? So share a bit more information and share the code you are running, since else we can't debug the issue well if we don't know where we are supposed to search

**Comment by CaptainKnuddel** [comment]
import openhivenpy as hiven

client = hiven.UserClient("Insert token")

@client.event()
async def on_ready():
    print("Bot is ready")

client.run()

Is used the standart code and you dont have to use "we" when you are alone

**Comment by Nicolas-Klatzer** [comment]
well yes but they are also here @Nxybi and they might know something, but alright

**Comment by Nicolas-Klatzer** [comment]
Still, please kindly follow the issue guidelines and add every piece of information so I can see it, so create a new issue please where I can then see everything. It might be a hassle but it can help me especially finding the issue. Since currently, I don't have a clue what might be wrong and information lacks a lot in your post, and it takes a lot of time to ask you for every information that should already be provided

**Comment by Nxybi** [comment]
Gonna hop in here and reopen - seems like an asyncio warning. More than likely - its an outdated asyncio. Care to share your asyncio version? (If you dont know how: google)

**Comment by Nicolas-Klatzer** [comment]
oh @Nxybi it was already resolved in #68

**Comment by Nxybi** [comment]
> oh @Nxybi it was already resolved in #68

you are bringing this up now
*after i was clearling my github notifications*

damnit kudo xD

**Comment by Nicolas-Klatzer** [comment]
As explained in #69: It was an issue with outdated asyncio, yes, but more it was dependent on the python version, since they only allow a certain asyncio version to be used and the features used by me was only available in versions for Python 3.8 or greater
